---
- name: Hello World!
  hosts: 184.72.119.162
  become: yes
 
  tasks:
 
  - name: Greetings 
    debug: msg="Hi! Stay Home, Stay Safe from COVID-19."

  - name: install apache latest version
    yum: name=httpd update_cache=yes state=latest

  - name: ensure apache is running
    service: name=httpd state=started
